In [ ]:
import numpy as np
import pandas as pd

In [ ]:
alpha = 1e-3
epsilon = 1e-3
weightsfinal =[]
biasfinal = 0

In [ ]:
def prediction(x, w, b=biasfinal):
  return x@w+b

In [ ]:
def forward_pass(X, Y, weights, bias):
  N = X.to_numpy() @ np.array(weights)
  P = N + bias
  diff = P - np.array(Y)
  loss = (diff @ diff.T)/ (2*len(Y))
  # print(loss)
  return P, loss

In [ ]:
def backward_pass(X, Y, weights, bias, P, loss):
  Tlp = (np.array(P - np.array(Y)))/len(Y)
  weight_gradient = ((X.to_numpy().T) @ Tlp)
  weights -= alpha * weight_gradient
  bias_gradient = np.sum(Tlp)
  bias -= alpha * bias_gradient
  return weights, bias

In [ ]:
def train(X, Y):
  global weightsfinal
  global biasfinal
  weights = 0.5*np.random.rand(len(X.columns))
  bias = np.random.rand(1)
  P, loss = forward_pass(X, Y, weights, bias)
  old = loss
  while (loss > 0) :
    weights, bias = backward_pass(X, Y, weights, bias, P, loss)
    P, loss = forward_pass(X, Y, weights, bias)
    if (abs(old - loss) <= epsilon):
      break
    old = loss
  weightsfinal = weights
  biasfinal = bias
  return weights, bias

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X1 = 10 * np.random.randn(200)
X2 = 10 * np.random.randn(200)
y = 100 * X1 - 200 * X2 + 5
data = np.column_stack((X1, X2, y))
df = pd.DataFrame(data, columns=["x1", "x2", "y"])
X = df[["x1", "x2"]]
y = df["y"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [ ]:
train(X_train, y_train)

(array([  99.99056827, -200.0042491 ]), array([3.99100835]))

In [ ]:
weightsfinal

array([  99.99056827, -200.0042491 ])

In [ ]:
biasfinal

array([3.99100835])

In [ ]:
y_pred = prediction(X_test,w=weightsfinal, b=biasfinal)

In [ ]:
losses = np.sum(abs(y_pred - y_test)/len(y_test))

In [ ]:
losses

1.0021663487765538

In [ ]:
y_test

37     1915.555370
109    3265.386004
31      748.954542
89     -218.927558
66    -2060.035445
119    -749.288145
54     1133.733019
74     3499.173948
145    1019.531491
142    -127.936230
148   -2544.927059
112    1370.804320
174   -1019.982104
55     1383.917706
141    -154.037735
149    1183.717740
25    -1988.018624
34     -174.943039
170     712.059301
39     -592.949039
172   -1929.256791
153    1748.766730
175   -1739.772325
61    -2059.330220
65     3514.967701
50    -3812.941616
42    -3581.271516
129   -1725.382190
179    3850.021159
2      -753.938835
12    -1087.166326
133   -1863.273057
90    -5231.225641
22      814.604458
41    -2128.024049
32    -3411.978935
125     -70.112169
196    2408.224687
158     124.980309
180   -2105.378203
Name: y, dtype: float64

In [ ]:
y_pred

37     1914.440186
109    3264.357784
31      747.931493
89     -219.944724
66    -2061.174256
119    -750.114541
54     1132.643594
74     3498.168515
145    1018.689710
142    -128.926006
148   -2546.110959
112    1369.731793
174   -1020.794253
55     1382.698410
141    -155.037438
149    1182.775339
25    -1989.117576
34     -176.056962
170     710.988968
39     -593.982547
172   -1929.940469
153    1747.944168
175   -1740.686225
61    -2060.435750
65     3513.781390
50    -3813.939824
42    -3582.269712
129   -1726.590041
179    3849.127219
2      -754.922583
12    -1088.004264
133   -1864.289279
90    -5232.126589
22      813.769844
41    -2129.040474
32    -3412.975181
125     -71.078052
196    2407.195667
158     123.864891
180   -2106.336282
dtype: float64